CREATE TABLE IF NOT EXISTS POOLEDPNRDATA (
  POOLEDPNRDATA_ID               BIGINT AUTO_INCREMENT,
  BRANCH_NAME                    VARCHAR(100) NOT NULL,
  PACKAGE_NAME                   VARCHAR(300) NOT NULL,
  TEST_ID                        VARCHAR(100) NOT NULL,
  PNR_LOCATOR                    VARCHAR(6)   NOT NULL,
  ENVIRONMENT                    VARCHAR(100) NOT NULL,
  AIRLINE                        VARCHAR(100) NOT NULL,
  DEPARTURE_DATE                 VARCHAR(100) NOT NULL,
  DEPARTURE_DATE_IN_MILLISECONDS BIGINT       NOT NULL,
  CREATION_TIME                  VARCHAR(100) NOT NULL,
  POOLED_TEST_DATA_ID            BIGINT,
  PRIMARY KEY (POOLEDPNRDATA_ID)
);

CREATE TABLE IF NOT EXISTS POOLED_TEST_DATA (
  POOLED_TEST_DATA_ID BIGINT AUTO_INCREMENT,
  TEST_DATA           CLOB NOT NULL,
  PRIMARY KEY (POOLED_TEST_DATA_ID)
);

CREATE TABLE IF NOT EXISTS PNR_CANCEL_DATA (
  PNRCANCELDATA_ID BIGINT AUTO_INCREMENT,
  PNR_LOCATOR      VARCHAR(6)   NOT NULL,
  CANCEL_TIME      VARCHAR(100) NOT NULL,
  ENVIRONMENT      VARCHAR(100) NOT NULL,
  AIRLINE          VARCHAR(100) NOT NULL,
  PRIMARY KEY (PNRCANCELDATA_ID)
);

CREATE TABLE IF NOT EXISTS PNR_STATISTICS (
  PNR_STATISTICS_ID BIGINT AUTO_INCREMENT,
  BRANCH_NAME       VARCHAR(100) NOT NULL,
  PACKAGE_NAME      VARCHAR(300) NOT NULL,
  TEST_ID           VARCHAR(100) NOT NULL,
  PNR_LOCATOR       VARCHAR(6)   NOT NULL,
  ENVIRONMENT       VARCHAR(100) NOT NULL,
  AIRLINE           VARCHAR(100) NOT NULL,
  CREATION_TIME     VARCHAR(100) NOT NULL,
  PULLED_PNR        BOOLEAN      NOT NULL,
  PRIMARY KEY (PNR_STATISTICS_ID)
);
