DROP TABLE MEAL;
CREATE TABLE MEAL (
  MEAL_ID               BIGINT AUTO_INCREMENT,
  START                 TIMESTAMP NOT NULL,
  DISH                    VARCHAR(100) NOT NULL,
  PRIMARY KEY (MEAL_ID)
);

DROP TABLE INCIDENT IF EXISTS;
CREATE TABLE INCIDENT (
  INCIDENT_ID               BIGINT AUTO_INCREMENT,
  START                 TIMESTAMP NOT NULL,
  REACTION                    VARCHAR(100) NOT NULL,
  PRIMARY KEY (INCIDENT_ID)
);

